### ISSUE TITLE
Refactor plugin codebase, improve performance

### ISSUE THREAD

**Issue by user-grinch** [user-grinch/ModelExtras#15]
There's a significant amount of impact with/ without ModelExtras.asi installed. This aims to resolve it.

### Requirements:

1. Redo the backend, which will require significant structure changes to plugin features
2. Instead of searching for entity RwFrames each render, cache the RwFrames
3. Keep compatibility with existing entity models
4. Make the plugin more in line with VehFuncs codebase (Possible merge of VehFuncs into ModelExtras in the future)
5. Create a scalable implementation. Keep the impact as low as possible with lots of adapted entities in render.
6. Use the AVS internals instead of custom code

### Benefits

1. Should increase performance drastically
2. Reduce shutters when TONs of adapted models are visible on the screen
3. Make the code more maintainable
4. Makes it easier to port features from VehFuncs

No, ETA at the moment. Feel free to offer advice.

**Comment by Crowdigger** [comment]
I don't think it's a good idea to try merging Vehfuncs with ModelExtras. Vehfuncs is already a stable mod, it works fine. You would just have unnecessary work, time that could be used for other things if you want.

**Comment by Crowdigger** [comment]
The difference is that Vehfuncs doesn't need maintenance. It works, it's stable, and it's correct. Trying to integrate it would be a waste of time because it's not necessary. And if a new function is needed and it's not part of Vehfuncs, it would simply be a matter of creating the new function for ModelExtras and using it alongside Vehfuncs for the functions it covers.

**Comment by Crowdigger** [comment]
> > I don't think it's a good idea to try merging Vehfuncs with ModelExtras. Vehfuncs is already a stable mod, it works fine. You would just have unnecessary work, time that could be used for other things if you want.
> 
> Well, AVS is good too? But merged to ModelExtras because AVS is not maintaining anymore. VehFuncs also not maintaining.

The difference is that Vehfuncs doesn't need maintenance. It works, it's stable, and it's correct. Trying to integrate it would be a waste of time because it's not necessary. And if a new function is needed and it's not part of Vehfuncs, it would simply be a matter of creating the new function for ModelExtras and using it alongside Vehfuncs for the functions it covers.
