### ISSUE TITLE
Light Shadows Position Bug

### ISSUE THREAD

**Issue by CanerKaraca23** [user-grinch/ModelExtras#29]
Positions are buggy also shadows are sometimes more than they should be.

https://discord.com/channels/689515979847237649/1129105388168556554/1286639169262719020

**Comment by user-grinch** [comment]
This is a tricky one. I have no clue on how to properly handle the rotations of the ImVehFt shadows since I don't know how DK calculated them. 

One of the alternatives I discussed with @KaiQ-1 few weeks back was this,
1. Disable shadows for ImVehFt shadows (will still be enable able if anyone wants from the ini)
2. Only show shadows for models that were adapted for ModelExtras in mind.

This is more like a patch than a fix but that's the best I could come up with. I'm open to suggestions/ ideas.

**Comment by CanerKaraca23** [comment]
> This is a tricky one. I have no clue on how to properly handle the rotations of the ImVehFt shadows since I don't know how DK calculated them.
> 
> One of the alternatives I discussed with @KaiQ-1 few weeks back was this,
> 
> 1. Disable shadows for ImVehFt shadows (will still be enable able if anyone wants from the ini)
> 2. Only show shadows for models that were adapted for ModelExtras in mind.
> 
> This is more like a patch than a fix but that's the best I could come up with. I'm open to suggestions/ ideas.

Actually, this issue happened after you implement this feature/fix https://github.com/user-grinch/ModelExtras/issues/16

maybe you should disable pivot thing on IVF vehicles.
